### ISSUE TITLE
Request for Pre-trained Checkpoint Release

### ISSUE THREAD

**Issue by function2-llx** [philip-mueller/chex#1]
Dear authors,

Thank you for the excellent work you've done with the CheX project and congratulations on the acceptance of your paper to ECCV 2024! I am currently working on a project that could greatly benefit from the use of your pre-trained model. Could you kindly provide an update on when we might expect the checkpoint to be available?

Thank you for your time and effort in making this resource available to the community.

Best regards

**Comment by philip-mueller** [comment]
We have now made the checkpoint of ChEX available.
Please follow the instructions in the README to download and use the checkpoint.
If you encounter any problems with the checkpoint, feel free to open a new issue.
